# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import actor_learner_pb2 as actor__learner__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in actor_learner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActorLearnerServiceStub(object):
    """============ 服务定义 ============

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTransitions = channel.unary_unary(
                '/actorlearner.ActorLearnerService/SendTransitions',
                request_serializer=actor__learner__pb2.TransitionBatch.SerializeToString,
                response_deserializer=actor__learner__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetWeights = channel.unary_unary(
                '/actorlearner.ActorLearnerService/GetWeights',
                request_serializer=actor__learner__pb2.WeightRequest.SerializeToString,
                response_deserializer=actor__learner__pb2.WeightsProto.FromString,
                _registered_method=True)
        self.CheckWeightsUpdate = channel.unary_unary(
                '/actorlearner.ActorLearnerService/CheckWeightsUpdate',
                request_serializer=actor__learner__pb2.WeightRequest.SerializeToString,
                response_deserializer=actor__learner__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/actorlearner.ActorLearnerService/HealthCheck',
                request_serializer=actor__learner__pb2.Empty.SerializeToString,
                response_deserializer=actor__learner__pb2.StatusResponse.FromString,
                _registered_method=True)


class ActorLearnerServiceServicer(object):
    """============ 服务定义 ============

    """

    def SendTransitions(self, request, context):
        """Actor -> Learner: 发送 transitions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWeights(self, request, context):
        """Actor <- Learner: 获取最新权重
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckWeightsUpdate(self, request, context):
        """Actor <- Learner: 轮询权重更新（返回是否有新版本）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActorLearnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTransitions': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTransitions,
                    request_deserializer=actor__learner__pb2.TransitionBatch.FromString,
                    response_serializer=actor__learner__pb2.StatusResponse.SerializeToString,
            ),
            'GetWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeights,
                    request_deserializer=actor__learner__pb2.WeightRequest.FromString,
                    response_serializer=actor__learner__pb2.WeightsProto.SerializeToString,
            ),
            'CheckWeightsUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckWeightsUpdate,
                    request_deserializer=actor__learner__pb2.WeightRequest.FromString,
                    response_serializer=actor__learner__pb2.StatusResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=actor__learner__pb2.Empty.FromString,
                    response_serializer=actor__learner__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'actorlearner.ActorLearnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('actorlearner.ActorLearnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActorLearnerService(object):
    """============ 服务定义 ============

    """

    @staticmethod
    def SendTransitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actorlearner.ActorLearnerService/SendTransitions',
            actor__learner__pb2.TransitionBatch.SerializeToString,
            actor__learner__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actorlearner.ActorLearnerService/GetWeights',
            actor__learner__pb2.WeightRequest.SerializeToString,
            actor__learner__pb2.WeightsProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckWeightsUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actorlearner.ActorLearnerService/CheckWeightsUpdate',
            actor__learner__pb2.WeightRequest.SerializeToString,
            actor__learner__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actorlearner.ActorLearnerService/HealthCheck',
            actor__learner__pb2.Empty.SerializeToString,
            actor__learner__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
