# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actor_learner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'actor_learner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61\x63tor_learner.proto\x12\x0c\x61\x63torlearner\"9\n\x0bTensorProto\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\r\n\x05\x64type\x18\x03 \x01(\t\"\x9e\x01\n\x0fTransitionProto\x12\x0b\n\x03obs\x18\x01 \x01(\x0c\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\x0c\x12\x15\n\rpolicy_action\x18\x03 \x01(\x0c\x12\x0e\n\x06reward\x18\x04 \x01(\x02\x12\x10\n\x08next_obs\x18\x05 \x01(\x0c\x12\x0c\n\x04\x64one\x18\x06 \x01(\x08\x12\x17\n\x0fis_intervention\x18\x07 \x01(\x08\x12\x0e\n\x06source\x18\x08 \x01(\t\"X\n\x0fTransitionBatch\x12\x32\n\x0btransitions\x18\x01 \x03(\x0b\x32\x1d.actorlearner.TransitionProto\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"\xd2\x01\n\x0cWeightsProto\x12=\n\nstate_dict\x18\x01 \x03(\x0b\x32).actorlearner.WeightsProto.StateDictEntry\x12\x0f\n\x07version\x18\x02 \x01(\x03\x12\x12\n\ntrain_step\x18\x03 \x01(\x03\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x1aK\n\x0eStateDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.actorlearner.TensorProto:\x02\x38\x01\"2\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\rWeightRequest\x12\x14\n\x0clast_version\x18\x01 \x01(\x03\"\x07\n\x05\x45mpty2\xbf\x02\n\x13\x41\x63torLearnerService\x12N\n\x0fSendTransitions\x12\x1d.actorlearner.TransitionBatch\x1a\x1c.actorlearner.StatusResponse\x12\x45\n\nGetWeights\x12\x1b.actorlearner.WeightRequest\x1a\x1a.actorlearner.WeightsProto\x12O\n\x12\x43heckWeightsUpdate\x12\x1b.actorlearner.WeightRequest\x1a\x1c.actorlearner.StatusResponse\x12@\n\x0bHealthCheck\x12\x13.actorlearner.Empty\x1a\x1c.actorlearner.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'actor_learner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEIGHTSPROTO_STATEDICTENTRY']._loaded_options = None
  _globals['_WEIGHTSPROTO_STATEDICTENTRY']._serialized_options = b'8\001'
  _globals['_TENSORPROTO']._serialized_start=37
  _globals['_TENSORPROTO']._serialized_end=94
  _globals['_TRANSITIONPROTO']._serialized_start=97
  _globals['_TRANSITIONPROTO']._serialized_end=255
  _globals['_TRANSITIONBATCH']._serialized_start=257
  _globals['_TRANSITIONBATCH']._serialized_end=345
  _globals['_WEIGHTSPROTO']._serialized_start=348
  _globals['_WEIGHTSPROTO']._serialized_end=558
  _globals['_WEIGHTSPROTO_STATEDICTENTRY']._serialized_start=483
  _globals['_WEIGHTSPROTO_STATEDICTENTRY']._serialized_end=558
  _globals['_STATUSRESPONSE']._serialized_start=560
  _globals['_STATUSRESPONSE']._serialized_end=610
  _globals['_WEIGHTREQUEST']._serialized_start=612
  _globals['_WEIGHTREQUEST']._serialized_end=649
  _globals['_EMPTY']._serialized_start=651
  _globals['_EMPTY']._serialized_end=658
  _globals['_ACTORLEARNERSERVICE']._serialized_start=661
  _globals['_ACTORLEARNERSERVICE']._serialized_end=980
# @@protoc_insertion_point(module_scope)
