"""
常量定义
"""

# 数据来源
SOURCE_DEMO = "demo"
SOURCE_ROLLOUT = "rollout"
SOURCE_INTERVENTION = "intervention"

# 动作空间
ACTION_SPACE_JOINT = "joint"
ACTION_SPACE_CARTESIAN = "cartesian"
ACTION_SPACE_DELTA_EE = "delta_ee"

# 默认值
DEFAULT_GAMMA = 0.99
DEFAULT_TAU = 0.005
DEFAULT_LEARNING_RATE = 3e-4
DEFAULT_BATCH_SIZE = 256
DEFAULT_BUFFER_SIZE = 1000000

# 日志
LOG_LEVEL_DEBUG = "DEBUG"
LOG_LEVEL_INFO = "INFO"
LOG_LEVEL_WARNING = "WARNING"
LOG_LEVEL_ERROR = "ERROR"
