"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class PolicyState(object):
    __slots__ = ["operator_type", "num_orders", "order_list"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.operator_type = ""
        self.num_orders = 0
        self.order_list = []

    def encode(self):
        buf = BytesIO()
        buf.write(PolicyState._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __operator_type_encoded = self.operator_type.encode('utf-8')
        buf.write(struct.pack('>I', len(__operator_type_encoded)+1))
        buf.write(__operator_type_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">i", self.num_orders))
        for i0 in range(self.num_orders):
            __order_list_encoded = self.order_list[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__order_list_encoded)+1))
            buf.write(__order_list_encoded)
            buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != PolicyState._get_packed_fingerprint():
            raise ValueError("Decode error")
        return PolicyState._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = PolicyState()
        __operator_type_len = struct.unpack('>I', buf.read(4))[0]
        self.operator_type = buf.read(__operator_type_len)[:-1].decode('utf-8', 'replace')
        self.num_orders = struct.unpack(">i", buf.read(4))[0]
        self.order_list = []
        for i0 in range(self.num_orders):
            __order_list_len = struct.unpack('>I', buf.read(4))[0]
            self.order_list.append(buf.read(__order_list_len)[:-1].decode('utf-8', 'replace'))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if PolicyState in parents: return 0
        tmphash = (0x3498f5a365c3aaa9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if PolicyState._packed_fingerprint is None:
            PolicyState._packed_fingerprint = struct.pack(">Q", PolicyState._get_hash_recursive([]))
        return PolicyState._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

