"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class PolicyAction(object):
    __slots__ = ["operator_type", "left_joint_action", "right_joint_action", "waist", "head", "publiser_name", "done"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.operator_type = ""
        self.left_joint_action = [ 0.0 for dim0 in range(8) ]
        self.right_joint_action = [ 0.0 for dim0 in range(8) ]
        self.waist = [ 0.0 for dim0 in range(3) ]
        self.head = [ 0.0 for dim0 in range(2) ]
        self.publiser_name = ""
        self.done = False

    def encode(self):
        buf = BytesIO()
        buf.write(PolicyAction._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __operator_type_encoded = self.operator_type.encode('utf-8')
        buf.write(struct.pack('>I', len(__operator_type_encoded)+1))
        buf.write(__operator_type_encoded)
        buf.write(b"\0")
        buf.write(struct.pack('>8d', *self.left_joint_action[:8]))
        buf.write(struct.pack('>8d', *self.right_joint_action[:8]))
        buf.write(struct.pack('>3d', *self.waist[:3]))
        buf.write(struct.pack('>2d', *self.head[:2]))
        __publiser_name_encoded = self.publiser_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__publiser_name_encoded)+1))
        buf.write(__publiser_name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack('b', self.done))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != PolicyAction._get_packed_fingerprint():
            raise ValueError("Decode error")
        return PolicyAction._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = PolicyAction()
        __operator_type_len = struct.unpack('>I', buf.read(4))[0]
        self.operator_type = buf.read(__operator_type_len)[:-1].decode('utf-8', 'replace')
        self.left_joint_action = struct.unpack('>8d', buf.read(64))
        self.right_joint_action = struct.unpack('>8d', buf.read(64))
        self.waist = struct.unpack('>3d', buf.read(24))
        self.head = struct.unpack('>2d', buf.read(16))
        __publiser_name_len = struct.unpack('>I', buf.read(4))[0]
        self.publiser_name = buf.read(__publiser_name_len)[:-1].decode('utf-8', 'replace')
        self.done = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if PolicyAction in parents: return 0
        tmphash = (0x19d671166b5eede5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if PolicyAction._packed_fingerprint is None:
            PolicyAction._packed_fingerprint = struct.pack(">Q", PolicyAction._get_hash_recursive([]))
        return PolicyAction._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

